config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index, :destroy] do
    resources :comments, only: :new
    post 'upvote', on: :member
    post 'downvote', on: :member
  end
  resources :comments, only: [:create, :show] do
    get 'new_nested', on: :member
    post 'upvote', on: :member
    post 'downvote', on: :member
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :author, :post, presence: true

  belongs_to :author, foreign_key: :user_id, primary_key: :id, class_name: User
  belongs_to :post
  has_many(
    :child_comments,
    foreign_key: :parent_comment_id,
    primary_key: :id,
    class_name: Comment
    )

  belongs_to(
    :parent_comment,
    foreign_key: :parent_comment_id,
    primary_key: :id,
    class_name: Comment
  )

  has_many :votes, as: :votable

  def score
    votes.pluck(:value).sum
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Post.find(params[:post_id]).comments.new
    render :new
  end

  def new_nested
    @comment = Comment.find(params[:id]).child_comments.new
    render :new_nested
  end

  def show
    @comment = Comment.find(params[:id])
    render :show
  end

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def comment_params
    params.require(:comment).permit(:post_id, :content, :parent_comment_id)
  end

  def upvote
    comment = Comment.find(params[:id])
    comment.votes.create!(value: 1)
    redirect_to post_url(comment.post)
  end

  def downvote
    comment = Comment.find(params[:id])
    comment.votes.create!(value: -1)
    redirect_to post_url(comment.post)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/new.html.erb
<h1>Write a Comment</h1>

<form action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
  <textarea name="comment[content]"></textarea>
  <input type="submit">
</form>

app/views/comments/new_nested.html.erb
<h1>Write a Reply</h1>

<form action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <input type="hidden"
         name="comment[post_id]"
         value="<%= @comment.parent_comment.post_id %>">
 <input type="hidden"
        name="comment[parent_comment_id]"
        value="<%= @comment.parent_comment_id %>">
  <textarea name="comment[content]"></textarea>
  <input type="submit">
</form>

app/views/comments/show.html.erb
<h1>Comment by <%= @comment.author.username %></h1>

<p><%= @comment.content %></p><br>
<%= button_to "Like", upvote_comment_url(@comment) %>
<%= button_to "Hate", downvote_comment_url(@comment) %>
Popularity: <%= @comment.score %>
<br>
<h2>Replies</h2>
<% @comment.child_comments.each do |comment| %>
  Comment by <%= comment.author.username.capitalize %>
  <br>
  <p><%= comment.content %></p>
  <%= link_to "Replies", comment_url(comment) %>
  <br>
  <br>
<% end %>

<%= link_to "Reply", new_nested_comment_url(@comment) %>