config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index, :destroy] do
    resources :comments, only: :new
    post 'upvote', on: :member
    post 'downvote', on: :member
  end
  resources :comments, only: [:create, :show] do
    get 'new_nested', on: :member
    post 'upvote', on: :member
    post 'downvote', on: :member
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_validation :ensure_session_token
  validates :username, :password_digest, presence: true
  validates :password, length: { minimum: 1, maximum: 6, allow_nil: true }

  attr_reader :password

  has_many :subs
  has_many :comments, inverse_of: :author
  has_many(
    :posts,
    foreign_key: :author_id,
    primary_key: :id,
    class_name: :Post
  )

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    if user && user.is_password?(password)
      user
    else
      nil
    end
  end

  def password=(input)
    @password = input
    self.password_digest = BCrypt::Password.create(input)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def is_password?(input)
    BCrypt::Password.new(self.password_digest).is_password?(input)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% action_url = logging_in ? session_url : users_url %>

<form action="<%= action_url %>" method = "POST" >

<%= auth_token %>

<label for = "user_name">Username:</label>
<input type = "text"
        name = "user[username]"
        value = "<%= user.username %>"
        id = "user_name"
        >
<br>

<label for = "user_password">Password:</label>
<input type = "password"
        name = "user[password]"
        id = "user_password"
        >
<br>

<input type="submit" value = "Submit!" >

</form>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<%= render "form", user: @user, logging_in: false %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username.capitalize %>!</h1>