config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index, :destroy] do
    resources :comments, only: :new
    post 'upvote', on: :member
    post 'downvote', on: :member
  end
  resources :comments, only: [:create, :show] do
    get 'new_nested', on: :member
    post 'upvote', on: :member
    post 'downvote', on: :member
  end
end

app/models/sub.rb
class Sub < ActiveRecord::Base

  validates :title, :description, :user_id, presence: true

  belongs_to(
    :moderator,
    foreign_key: :user_id,
    primary_key: :id,
    class_name: User
  )

  has_many :posts, through: :post_subs, source: :post
  has_many :post_subs

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :redirect_unless_moderator, only: [:edit, :update]
  before_action :redirect_unless_logged_in, only: [:new, :create]

  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = current_user.subs.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def redirect_unless_moderator
    redirect_to subs_url unless current_user == Sub.find(params[:id]).moderator
  end


end

app/helpers/subs_helper.rb
module SubsHelper
  def is_moderator?(sub)
    current_user == sub.moderator
  end
end

app/views/subs/_form.html.erb
<% method_type = sub.persisted? ? "patch" : "post" %>
<% action_url = sub.persisted? ? sub_url(sub) : subs_url %>

<form action=<%= action_url %> method="post">
  <input type="hidden" name="_method" value=<%= method_type %>>
  <%= auth_token %>

  <label for="sub_title">Title</label>
  <input type="text" name="sub[title]" value="<%=sub.title%>" id="sub_title">

  <label for="sub_description">Description</label>
  <textarea name = "sub[description]" value = "<%= sub.description %>" id="sub_description">
  </textarea>

  <input type="submit" >

</form>

app/views/subs/_post.html.erb
<%= link_to post.title, post_url(post) %>
<%= button_to "Like", upvote_post_url(post) %>
<%= button_to "Hate", downvote_post_url(post) %>
Popularity: <%= post.score %>
<br>

app/views/subs/_sub.html.erb
<li><%= link_to sub.title, sub_url(sub) %></li>

app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<%= render "form", sub: @sub %>

app/views/subs/index.html.erb
<h1>Sub Index</h1>

  <font color = "Red"><%= render @subs %></font color>

<br>
<%= link_to "<< Create Sub", new_sub_url if logged_in?%>
<br>
<%= link_to "<< Create Post", new_post_url if logged_in?%>

app/views/subs/new.html.erb
<h1>Create a New Sub!</h1>

<%= render "form", sub: @sub %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<p><%= @sub.description %></p>

<br><br><br>
<% collection = @sub.posts.sort_by { |post| post.score }.reverse %>
<%= render partial: "post", collection: collection, as: :post %>
<br><br><br><br>

<%= button_to "Create a Post!", new_post_url, method: :get %>
<br>
<%= link_to "<< Edit Sub", edit_sub_url(@sub) if is_moderator?(@sub)%>