config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index, :destroy] do
    resources :comments, only: :new
    post 'upvote', on: :member
    post 'downvote', on: :member
  end
  resources :comments, only: [:create, :show] do
    get 'new_nested', on: :member
    post 'upvote', on: :member
    post 'downvote', on: :member
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :subs, :author, presence: true
  belongs_to(
    :author,
    foreign_key: :author_id,
    primary_key: :id,
    class_name: :User
  )

  has_many :post_subs
  has_many :subs, through: :post_subs, source: :sub
  has_many :comments
  has_many :votes, as: :votable

  def comments_by_parent_id
    hash = Hash.new { |h, k| h[k] = [] }
    comments.each do |comment|
      hash[comment.parent_comment_id] << comment
    end
    hash
  end

  def score
    votes.pluck(:value).sum
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :redirect_unless_logged_in, except: :show
  before_action :redirect_unless_author, only: [:edit, :update]
  def new
    @post = Post.new
    render :new
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end

  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end

  end

  def show
    @post = Post.find(params[:id])
    @comments_hash = @post.comments_by_parent_id
    render :show
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_ids => [])
  end

  def redirect_unless_author
    redirect_to subs_url unless current_user == Post.find(params[:id]).author
  end

  def upvote
    post = Post.find(params[:id])
    post.votes.create!(value: 1)
    redirect_to post_url(post)
  end

  def downvote
    post = Post.find(params[:id])
    post.votes.create!(value: -1)
    redirect_to post_url(post)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
Comment by <%= comment.author.username.capitalize %>
at <%= comment.created_at %>
<br>
<p><%= comment.content %></p>
<%= link_to "Comment", comment_url(comment) %>
<br>
<%= button_to "Like", upvote_comment_url(comment) %>
<%= button_to "Hate", downvote_comment_url(comment) %>
Popularity: <%= comment.score %>
<br>
<br>

<ul>
<% @comments_hash[comment.id]
   .sort_by { |comment| comment.score }
   .reverse
   .each do |comment2| %>
  <% if comment2.parent_comment_id == comment.id %>
    <li>
      <%= render "comment", comment: comment2 %>
    </li>
  <% end %>
<% end %>
</ul>

app/views/posts/_form.html.erb
<% action_url = post.persisted? ? post_url(post) : posts_url %>
<% method_type = post.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= method_type %>">

  <%= auth_token %>

  <label for="post_title">Title: </label>
  <input type="text" name="post[title]" value="<%= post.title %>" id="post_title">
  <br>
  <label for="post_url">URL: </label>
  <input type="text" name="post[url]" value="<%= post.url %>" id="post_url">
  <br>
  <label for="content">Content: </label>
  <textarea name="post[content]" id="content"><%= post.content %></textarea>
  <br>
  <label>Sub: </label>
  <% Sub.all.each do |sub| %>
    <input type="checkbox"
           name="post[sub_ids][]"
           id="sub_id_<%=sub.id%>"
           value=<%=sub.id%>
           <%= "checked" if post.sub_ids.include?(sub.id) %>
           >
    <label for="sub_id_<%=sub.id%>"><%=sub.title%></label>
  <% end %>
  <br>
  <input type="submit">
</form>

app/views/posts/edit.html.erb
<h1>Edit Your Post!</h1>

<%= render "form", post: @post %>

app/views/posts/new.html.erb
<h1> Write Your Post!</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h4>Author: <%= @post.author.username %></h4>
<%= link_to "is this true? click here", link_helper(@post.url) %>
<br><br>
<%= @post.content %>
<br><br>

<%= button_to "Like", upvote_post_url(@post) %>
<%= button_to "Hate", downvote_post_url(@post) %>
Popularity: <%= @post.score %>
<br><br><br><font color = "Red">

<left>
<ul>
<% @comments_hash[nil]
   .sort_by { |comment| comment.score }
   .reverse
   .each do |comment| %>
  <li><%= render "comment", comment: comment %></li>
<% end %>
</ul>
</left>
<br><br><br></font color>

<%= link_to "<< Write Comment", new_post_comment_url(@post) %>
<br><br><br>
<%= link_to "<< Edit Post",
edit_post_url(@post) if current_user == @post.author %><br>

<br><br><br>
Sub List:
<br>
<% @post.subs.each do |sub| %>
  <%= link_to "<< To #{sub.title}", sub_url(sub) %>
  <br>
<% end %>